"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Space = exports.Slider = exports.Skeleton = exports.Select = exports.Row = exports.Result = exports.Rate = exports.Radio = exports.Progress = exports.Popover = exports.Popconfirm = exports.Pagination = exports.PageHeader = exports.notification = exports.Statistic = exports.Modal = exports.Mentions = exports.Menu = exports.message = exports.List = exports.Layout = exports.InputNumber = exports.Image = exports.Input = exports.Grid = exports.Form = exports.Empty = exports.Drawer = exports.Dropdown = exports.Divider = exports.Descriptions = exports.DatePicker = exports.ConfigProvider = exports.Comment = exports.Col = exports.Checkbox = exports.Cascader = exports.Carousel = exports.Collapse = exports.Card = exports.Calendar = exports.Button = exports.Breadcrumb = exports.Badge = exports.BackTop = exports.Avatar = exports.Alert = exports.AutoComplete = exports.Anchor = exports.Affix = void 0;
exports.version = exports.Upload = exports.Typography = exports.Tooltip = exports.Timeline = exports.TimePicker = exports.Tag = exports.Tabs = exports.TreeSelect = exports.Tree = exports.Transfer = exports.Table = exports.Switch = exports.Steps = exports.Spin = void 0;
var affix_1 = require("antd/lib/affix");
Object.defineProperty(exports, "Affix", { enumerable: true, get: function () { return __importDefault(affix_1).default; } });
var anchor_1 = require("antd/lib/anchor");
Object.defineProperty(exports, "Anchor", { enumerable: true, get: function () { return __importDefault(anchor_1).default; } });
var auto_complete_1 = require("antd/lib/auto-complete");
Object.defineProperty(exports, "AutoComplete", { enumerable: true, get: function () { return __importDefault(auto_complete_1).default; } });
var alert_1 = require("antd/lib/alert");
Object.defineProperty(exports, "Alert", { enumerable: true, get: function () { return __importDefault(alert_1).default; } });
var avatar_1 = require("antd/lib/avatar");
Object.defineProperty(exports, "Avatar", { enumerable: true, get: function () { return __importDefault(avatar_1).default; } });
var back_top_1 = require("antd/lib/back-top");
Object.defineProperty(exports, "BackTop", { enumerable: true, get: function () { return __importDefault(back_top_1).default; } });
var badge_1 = require("antd/lib/badge");
Object.defineProperty(exports, "Badge", { enumerable: true, get: function () { return __importDefault(badge_1).default; } });
var breadcrumb_1 = require("antd/lib/breadcrumb");
Object.defineProperty(exports, "Breadcrumb", { enumerable: true, get: function () { return __importDefault(breadcrumb_1).default; } });
var button_1 = require("antd/lib/button");
Object.defineProperty(exports, "Button", { enumerable: true, get: function () { return __importDefault(button_1).default; } });
var calendar_1 = require("antd/lib/calendar");
Object.defineProperty(exports, "Calendar", { enumerable: true, get: function () { return __importDefault(calendar_1).default; } });
var card_1 = require("antd/lib/card");
Object.defineProperty(exports, "Card", { enumerable: true, get: function () { return __importDefault(card_1).default; } });
var collapse_1 = require("antd/lib/collapse");
Object.defineProperty(exports, "Collapse", { enumerable: true, get: function () { return __importDefault(collapse_1).default; } });
var carousel_1 = require("antd/lib/carousel");
Object.defineProperty(exports, "Carousel", { enumerable: true, get: function () { return __importDefault(carousel_1).default; } });
var cascader_1 = require("antd/lib/cascader");
Object.defineProperty(exports, "Cascader", { enumerable: true, get: function () { return __importDefault(cascader_1).default; } });
var checkbox_1 = require("antd/lib/checkbox");
Object.defineProperty(exports, "Checkbox", { enumerable: true, get: function () { return __importDefault(checkbox_1).default; } });
var col_1 = require("antd/lib/col");
Object.defineProperty(exports, "Col", { enumerable: true, get: function () { return __importDefault(col_1).default; } });
var comment_1 = require("antd/lib/comment");
Object.defineProperty(exports, "Comment", { enumerable: true, get: function () { return __importDefault(comment_1).default; } });
var config_provider_1 = require("antd/lib/config-provider");
Object.defineProperty(exports, "ConfigProvider", { enumerable: true, get: function () { return __importDefault(config_provider_1).default; } });
var date_picker_1 = require("antd/lib/date-picker");
Object.defineProperty(exports, "DatePicker", { enumerable: true, get: function () { return __importDefault(date_picker_1).default; } });
var descriptions_1 = require("antd/lib/descriptions");
Object.defineProperty(exports, "Descriptions", { enumerable: true, get: function () { return __importDefault(descriptions_1).default; } });
var divider_1 = require("antd/lib/divider");
Object.defineProperty(exports, "Divider", { enumerable: true, get: function () { return __importDefault(divider_1).default; } });
var dropdown_1 = require("antd/lib/dropdown");
Object.defineProperty(exports, "Dropdown", { enumerable: true, get: function () { return __importDefault(dropdown_1).default; } });
var drawer_1 = require("antd/lib/drawer");
Object.defineProperty(exports, "Drawer", { enumerable: true, get: function () { return __importDefault(drawer_1).default; } });
var empty_1 = require("antd/lib/empty");
Object.defineProperty(exports, "Empty", { enumerable: true, get: function () { return __importDefault(empty_1).default; } });
var form_1 = require("antd/lib/form");
Object.defineProperty(exports, "Form", { enumerable: true, get: function () { return __importDefault(form_1).default; } });
var grid_1 = require("antd/lib/grid");
Object.defineProperty(exports, "Grid", { enumerable: true, get: function () { return __importDefault(grid_1).default; } });
var input_1 = require("antd/lib/input");
Object.defineProperty(exports, "Input", { enumerable: true, get: function () { return __importDefault(input_1).default; } });
var image_1 = require("antd/lib/image");
Object.defineProperty(exports, "Image", { enumerable: true, get: function () { return __importDefault(image_1).default; } });
var input_number_1 = require("antd/lib/input-number");
Object.defineProperty(exports, "InputNumber", { enumerable: true, get: function () { return __importDefault(input_number_1).default; } });
var layout_1 = require("antd/lib/layout");
Object.defineProperty(exports, "Layout", { enumerable: true, get: function () { return __importDefault(layout_1).default; } });
var list_1 = require("antd/lib/list");
Object.defineProperty(exports, "List", { enumerable: true, get: function () { return __importDefault(list_1).default; } });
var message_1 = require("antd/lib/message");
Object.defineProperty(exports, "message", { enumerable: true, get: function () { return __importDefault(message_1).default; } });
var menu_1 = require("antd/lib/menu");
Object.defineProperty(exports, "Menu", { enumerable: true, get: function () { return __importDefault(menu_1).default; } });
var mentions_1 = require("antd/lib/mentions");
Object.defineProperty(exports, "Mentions", { enumerable: true, get: function () { return __importDefault(mentions_1).default; } });
var modal_1 = require("antd/lib/modal");
Object.defineProperty(exports, "Modal", { enumerable: true, get: function () { return __importDefault(modal_1).default; } });
var statistic_1 = require("antd/lib/statistic");
Object.defineProperty(exports, "Statistic", { enumerable: true, get: function () { return __importDefault(statistic_1).default; } });
var notification_1 = require("antd/lib/notification");
Object.defineProperty(exports, "notification", { enumerable: true, get: function () { return __importDefault(notification_1).default; } });
var page_header_1 = require("antd/lib/page-header");
Object.defineProperty(exports, "PageHeader", { enumerable: true, get: function () { return __importDefault(page_header_1).default; } });
var pagination_1 = require("antd/lib/pagination");
Object.defineProperty(exports, "Pagination", { enumerable: true, get: function () { return __importDefault(pagination_1).default; } });
var popconfirm_1 = require("antd/lib/popconfirm");
Object.defineProperty(exports, "Popconfirm", { enumerable: true, get: function () { return __importDefault(popconfirm_1).default; } });
var popover_1 = require("antd/lib/popover");
Object.defineProperty(exports, "Popover", { enumerable: true, get: function () { return __importDefault(popover_1).default; } });
var progress_1 = require("antd/lib/progress");
Object.defineProperty(exports, "Progress", { enumerable: true, get: function () { return __importDefault(progress_1).default; } });
var radio_1 = require("antd/lib/radio");
Object.defineProperty(exports, "Radio", { enumerable: true, get: function () { return __importDefault(radio_1).default; } });
var rate_1 = require("antd/lib/rate");
Object.defineProperty(exports, "Rate", { enumerable: true, get: function () { return __importDefault(rate_1).default; } });
var result_1 = require("antd/lib/result");
Object.defineProperty(exports, "Result", { enumerable: true, get: function () { return __importDefault(result_1).default; } });
var row_1 = require("antd/lib/row");
Object.defineProperty(exports, "Row", { enumerable: true, get: function () { return __importDefault(row_1).default; } });
var select_1 = require("antd/lib/select");
Object.defineProperty(exports, "Select", { enumerable: true, get: function () { return __importDefault(select_1).default; } });
var skeleton_1 = require("antd/lib/skeleton");
Object.defineProperty(exports, "Skeleton", { enumerable: true, get: function () { return __importDefault(skeleton_1).default; } });
var slider_1 = require("antd/lib/slider");
Object.defineProperty(exports, "Slider", { enumerable: true, get: function () { return __importDefault(slider_1).default; } });
var space_1 = require("antd/lib/space");
Object.defineProperty(exports, "Space", { enumerable: true, get: function () { return __importDefault(space_1).default; } });
var spin_1 = require("antd/lib/spin");
Object.defineProperty(exports, "Spin", { enumerable: true, get: function () { return __importDefault(spin_1).default; } });
var steps_1 = require("antd/lib/steps");
Object.defineProperty(exports, "Steps", { enumerable: true, get: function () { return __importDefault(steps_1).default; } });
var switch_1 = require("antd/lib/switch");
Object.defineProperty(exports, "Switch", { enumerable: true, get: function () { return __importDefault(switch_1).default; } });
var table_1 = require("antd/lib/table");
Object.defineProperty(exports, "Table", { enumerable: true, get: function () { return __importDefault(table_1).default; } });
var transfer_1 = require("antd/lib/transfer");
Object.defineProperty(exports, "Transfer", { enumerable: true, get: function () { return __importDefault(transfer_1).default; } });
var tree_1 = require("antd/lib/tree");
Object.defineProperty(exports, "Tree", { enumerable: true, get: function () { return __importDefault(tree_1).default; } });
var tree_select_1 = require("antd/lib/tree-select");
Object.defineProperty(exports, "TreeSelect", { enumerable: true, get: function () { return __importDefault(tree_select_1).default; } });
var tabs_1 = require("antd/lib/tabs");
Object.defineProperty(exports, "Tabs", { enumerable: true, get: function () { return __importDefault(tabs_1).default; } });
var tag_1 = require("antd/lib/tag");
Object.defineProperty(exports, "Tag", { enumerable: true, get: function () { return __importDefault(tag_1).default; } });
var time_picker_1 = require("antd/lib/time-picker");
Object.defineProperty(exports, "TimePicker", { enumerable: true, get: function () { return __importDefault(time_picker_1).default; } });
var timeline_1 = require("antd/lib/timeline");
Object.defineProperty(exports, "Timeline", { enumerable: true, get: function () { return __importDefault(timeline_1).default; } });
var tooltip_1 = require("antd/lib/tooltip");
Object.defineProperty(exports, "Tooltip", { enumerable: true, get: function () { return __importDefault(tooltip_1).default; } });
var typography_1 = require("antd/lib/typography");
Object.defineProperty(exports, "Typography", { enumerable: true, get: function () { return __importDefault(typography_1).default; } });
var upload_1 = require("antd/lib/upload");
Object.defineProperty(exports, "Upload", { enumerable: true, get: function () { return __importDefault(upload_1).default; } });
var version_1 = require("antd/lib/version");
Object.defineProperty(exports, "version", { enumerable: true, get: function () { return __importDefault(version_1).default; } });
